### PR TITLE
Card Client Confirm Payment Source

### PR DESCRIPTION
**Pull request by sshropshire**
### Reason for changes

This PR updates the CardClient API to better align with the Orders v2 API. In the future, we may revisit API naming to improve the developer experience.

### Summary of changes

- Rename CardClient `approveOrder` method to `confirmPaymentSource`

### Checklist

~- [ ] Added a changelog entry~

### CODE REVIEW

**Review by jaxdesmarais — COMMENTED** [review]
I think we also need to [update the language in the title here](https://github.com/paypal/iOS-SDK/blob/0355073bc53ef52cc4bc546236e03998f6a9fbaa/Demo/Demo/ViewModels/BaseViewModel.swift#L104) as well as in the [card](https://github.com/paypal/iOS-SDK/blob/a115b8e037b626a4add4bdb9d97c4acc6467372b/docs/Card/integration.md) and [PayPal](https://github.com/paypal/iOS-SDK/blob/f772c94e1ce9db4a8adb65c6e4a6772dcdcc0e08/docs/PayPal/integration.md) integration guide

**Comment by sshropshire** [comment]
> I think we also need to [update the language in the title here](https://github.com/paypal/iOS-SDK/blob/0355073bc53ef52cc4bc546236e03998f6a9fbaa/Demo/Demo/ViewModels/BaseViewModel.swift#L104) as well as in the [card](https://github.com/paypal/iOS-SDK/blob/a115b8e037b626a4add4bdb9d97c4acc6467372b/docs/Card/integration.md) and [PayPal](https://github.com/paypal/iOS-SDK/blob/f772c94e1ce9db4a8adb65c6e4a6772dcdcc0e08/docs/PayPal/integration.md) integration guide

That's a good call. I'll update.

**Comment by sshropshire** [comment]
@jaxdesmarais I ended up leaving the PayPal integration guide intact since it isn't using the orders v2 `confirm-payment-source` endpoint directly.

**Comment by sarahkoop** [comment]
I'm not sure we need to change this merchant facing method name. I think the issue was that the demo app incorrectly says "APPROVE" when it should say "CONFIRM".

**Comment by sarahkoop** [comment]
I'm not sure we need to change this merchant facing method name. I think the issue was that the demo app incorrectly says "APPROVE" when it should say "CONFIRM".

**Comment by sshropshire** [comment]
@sarahkoop oh ok we might have to sync then. I'm cool with nuking this one and opening up a new PR.

**Pull request closed without merging**
