### PR TITLE
Remove UIKit Option in Demo App

### PR DESCRIPTION
**Pull request by KunJeongPark**
### Summary of changes

- Removed UIKit option in demo app in settings 
- Remove UIKit ViewControllers used for UIKit option
- Removed enum DemoUIFramework 

### Checklist

~- [ ] Added a changelog entry~

### Authors
- @KunJeongPark

### CODE REVIEW

**Review by jaxdesmarais — COMMENTED** [review]
This can be a follow up PR or in this PR but we should convert `FeatureBaseViewController`, `ViewController`, and remove `FeatureBaseViewControllerRepresentable`. Those 3 were all used for interoperability and sharing components across SwiftUI and UIKit. Since we want to take a SwiftUI first approach we should move these all into SwiftUI vs mixing the two.

**Comment by scannillo** [comment]
Just pulled this down, it looks awesome 👏.

I see that we still are specifying `UIKit` in this [UI Test](https://github.com/paypal/iOS-SDK/blob/b3dbc6523f323003b4ccd10400d258dc06e84375/Demo/DemoUITests/CardUITests.swift#L11). We should update this to SwiftUI - but it looks like this UI test isn't even running on CI, it's probably pretty outdated.

**Review by scannillo — APPROVED** [review]
Looks great! Left a small comment about a UI test

**Review by jaxdesmarais — APPROVED** [review]

**Comment by KunJeongPark** [comment]
> Just pulled this down, it looks awesome 👏.
> 
> I see that we still are specifying `UIKit` in this [UI Test](https://github.com/paypal/iOS-SDK/blob/b3dbc6523f323003b4ccd10400d258dc06e84375/Demo/DemoUITests/CardUITests.swift#L11). We should update this to SwiftUI - but it looks like this UI test isn't even running on CI, it's probably pretty outdated.

Thank you Sammy! Good call. I saw that the test is failing on main as well with SwiftUI option and for UIKit option. I will make a separate ticket for this UI test.

**Pull request merged**
